### ISSUE TITLE
Excessive Crimson Cult portals above Surface

### ISSUE THREAD

**Issue by legendblade** [Rosethorns/CUTSAshes#1]
While flying around in one test world, I noticed that there was a couple of Crimson Cult portals near each other on the same screen - unsure if this is actually an issue, or just standard Thaumcraft behavior, but it brings up the question of if portals should be blocked over Y:60 as well.

**Comment by Rosethorns** [comment]
I will keep an eye out when I next launch

**Comment by Rosethorns** [comment]
Have not experienced this since the issue went up. I will keep this open for now but the issue is on the clock

**Comment by legendblade** [comment]
I have a feeling this was just a one-off bit of "luck". I also haven't seen it since, so, I'm going to close it out.
