### ISSUE TITLE
Ores Issues List

### ISSUE THREAD

**Issue by legendblade** [Rosethorns/CUTSAshes#10]
Gregify:
- [x] Thaumcraft Amber
- [x] Thaumcraft Cinnabar
- [x] Earthworks Blue/Green/Purple Shale
- [x] Rustic Slate
- [ ] Astral Aquamarine?

Remove:
- [x] AE's version of Certus Quartz
- [x] Wings Fairy Ore
- [x] Wings Amethyst
- [x] BoP gem ores
- [x] Astral Sorcery Marble
- [x] Chisel Marble. Add chisel support for UB->Astral/Chisel
- [x] Chisel Limestone in favor of UB's limestone. Add chisel support.
- [x] Greg Black Granite in favor of UB's red granite. Add chisel support.
- [x] Greg Red Granite in favor of UB's black granite. Add chisel support.
- [x] Greg Marble in favor of UB's marble. Add chisel support.
- [x] Quark Basalt; leave Chisel Basalt. Add chisel support for UB basalt.
- [x] Mystic World Amethyst
- [x] Mystic World Silver

Undecided:
- ~~Soot sulfur - there's a greg version, but these are more traps than anything else?~~

**Comment by legendblade** [comment]
Add additional chisel variants for processed UB stones as well.

**Comment by legendblade** [comment]
BoP gem ores are removed dependent upon using BoP world type.

... <sigh>

**Comment by duely** [comment]
[This (fucku.py.txt)](https://github.com/Rosethorns/CUTSAshes/files/3365107/fucku.py.txt) is my python script for stripping out BoP generators from every biome based on the generator name. We could use this to generate custom override biome files that don't have any of the BoP ore gen, even if you aren't using the BoP world type (it works for my climatic biomes placement world type).

**Comment by legendblade** [comment]
Thanks; I'll port that over into the JS worldgen script I have and update the biome defs from that.

**Comment by legendblade** [comment]
Done in fdd0d7f6ae94fd6478e45faa7274bae024a68cd3

**Comment by duely** [comment]
You can also use it to disable quicksand in the overworld biomes

**Comment by legendblade** [comment]
I believe this is good and completed at this point; we'll see how people feel about the aquamarine in testing.
