### ISSUE TITLE
Highlands biome mostly GTCE Rubber Trees

### ISSUE THREAD

**Issue by legendblade** [Rosethorns/CUTSAshes#2]
Highlands biomes have most of their trees as rubber trees.

**Version**: 0.4

**Expected Result**: Rubber trees are suitably rare

**Actual Result**: Rubber trees vastly outnumber all other tree types in Highlands biome

**Comment by Rosethorns** [comment]
I did notice that. I think greg just adds worldgen rubber trees to all biomes. I will check if there is a way to keep them out of non-tree baring biomes.

**Comment by Rosethorns** [comment]
We will have to live with rubber trees being everywhere as GTCE is either "on" or "off" and I am not willing to get worldtweaker just to reorganize rubber tree spawns
