### ISSUE TITLE
Fix Greg Ore Colors Assigned in Scannable Configs

### ISSUE THREAD

**Issue by legendblade** [Rosethorns/CUTSAshes#3]
~~Currently, Scannable is configured to list all ore types as common ores, making the rare ore card useless. Is this intended behavior?~~

Per the below, need to resolve greg ore coloration.

**Comment by Rosethorns** [comment]
Not pictures is that I left platinum/rutile/gem baring ores out of the common ores filter. This makes them auto show up on the rare scanner.
What is missing however is those rare greg ores correct colors being assigned in the color list of of the config.

**Comment by legendblade** [comment]
Aha.

That's actually brings up the fact that they then won't be in the Astral Sorcery list, because that's where I took the source for that from.

**Comment by Rosethorns** [comment]
I only wanted common ores in the astral list ;)

**Comment by legendblade** [comment]
Closed in a4029e7
