### ISSUE TITLE
Add ways to disassemble old machines

### ISSUE THREAD

**Issue by legendblade** [Rosethorns/CUTSAshes#4]
One of the complaints I've heard from the people playing OmniFactory on my Discord is that once you're done with a machine, it becomes completely useless. Would it be worthwhile to add in a way to recycle old machines to recover (some) parts (at a reasonably suitable rate)?

This would be one instance where Artisan tables would really shine, but, that's a discussion for a later pack. :)

**Comment by Rosethorns** [comment]
Hey if you wanna handle the artisans table integration I am all for it ;) 
That being said yeah I think /some/ way to use the old machines is good. There is of course of old way of using the old machine in place of the new machines "hull" slot but yeah I dunno if that then makes the new machine accidentally cheaper xD

**Comment by legendblade** [comment]
Closed in 96e136499ba7cc215162bdf03c3066d6b7c6e827 (don't go there, 'tis a scary place)
