### ISSUE TITLE
Disable Thaumic JEI from recreating aspect list everytime

### ISSUE THREAD

**Issue by legendblade** [Rosethorns/CUTSAshes#6]
Thaumic JEI has a setting that causes it to regen the itemstack json every time; once we're sure the modlist is set, this should be flipped to false:

```
    # If true the Aspect from ItemStack json will be created always on startup, if false if will be only be created if it doesn't exist
    B:alwaysRecreateAspectFromItemStackFile=true
```

**Comment by Rosethorns** [comment]
This is on the TODO project

**Comment by legendblade** [comment]
I'll close it out here then so we're not keeping track of it in separate spots.
