### ISSUE TITLE
Ensure Radioactive Blocks/Materials in GTCE have Radiation

### ISSUE THREAD

**Issue by legendblade** [Rosethorns/CUTSAshes#9]
- Uraninite
- Pitchblende

**Comment by Rosethorns** [comment]
Uraninite complete

**Comment by legendblade** [comment]
I believe Uraninite is still missing the processed products (crushed, dusts, etc) but has the ores and block.

There are some other ores that (may) have an output of Thorium/Uranium/etc that might be a couple of processing steps - I'll get a more comprehensive list once I'm further into the processing lists.
